services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3cr3t
    ports:
      - "5435:5432"
    volumes:
      - ./data/db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  alembic:
    build:
      context: ./
      dockerfile: ./alembic/Dockerfile
    environment:
      - CHAI_DATABASE_URL=postgresql://postgres:s3cr3t@db:5432/chai
      - PGPASSWORD=s3cr3t
    depends_on:
      db:
        condition: service_healthy
    working_dir: /alembic
    entrypoint: ["./run_migrations.sh"]

  pipeline:
    build: src
    environment:
      - CHAI_DATABASE_URL=postgresql://postgres:s3cr3t@db:5432/chai
      - PKG_MANAGER=${PKG_MANAGER:-crates}
      - PYTHONPATH=/app
      - DEPENDENCIES=${DEPENDENCIES:-false}
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    entrypoint: ["./src/run_pipeline.sh"]

  monitor:
    build: monitor
    environment:
      - DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}
    volumes:
      - ./monitor:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      pipeline:
        condition: service_started
    working_dir: /usr/src/monitor
    entrypoint: ["./run_monitor.sh"]
