"""add-legacy-dependency-table

Revision ID: 89af630dc946
Revises: 238d591d5310
Create Date: 2025-03-12 00:45:35.727521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89af630dc946'
down_revision: Union[str, None] = '238d591d5310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type_id', sa.UUID(), nullable=False),
    sa.Column('semver_range', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['packages.id'], name=op.f('fk_legacy_dependencies_dependency_id_packages')),
    sa.ForeignKeyConstraint(['dependency_type_id'], ['depends_on_types.id'], name=op.f('fk_legacy_dependencies_dependency_type_id_depends_on_types')),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_legacy_dependencies_package_id_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_dependencies')),
    sa.UniqueConstraint('package_id', 'dependency_id', name='uq_package_dependency')
    )
    op.create_index(op.f('ix_legacy_dependencies_dependency_id'), 'legacy_dependencies', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_legacy_dependencies_dependency_type_id'), 'legacy_dependencies', ['dependency_type_id'], unique=False)
    op.create_index(op.f('ix_legacy_dependencies_package_id'), 'legacy_dependencies', ['package_id'], unique=False)
    op.drop_table('temp_import')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_import',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('derived_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('package_manager_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('import_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('readme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f('ix_legacy_dependencies_package_id'), table_name='legacy_dependencies')
    op.drop_index(op.f('ix_legacy_dependencies_dependency_type_id'), table_name='legacy_dependencies')
    op.drop_index(op.f('ix_legacy_dependencies_dependency_id'), table_name='legacy_dependencies')
    op.drop_table('legacy_dependencies')
    # ### end Alembic commands ###
